version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    tty: true
    container_name: competitive-programing-api-container
    hostname: competitive-programing-api-server
    environment:
      ENV: development
    ports:
      - 8080:8080
    depends_on:
      - db
